spring.application.name=Practice

spring.datasource.url=mysql://un8e5cfrmjrywoaa:Az9cX49XB5nq6MJRHkDj@bpnf3dbzs5do3p3nbolh-mysql.services.clever-cloud.com:3306/bpnf3dbzs5do3p3nbolh
spring.datasource.username=un8e5cfrmjrywoaa
spring.datasource.password=Az9cX49XB5nq6MJRHkDj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=${PORT:8080}
